// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CrackMnemonic(arg1, arg2) {
  return window['go']['main']['App']['CrackMnemonic'](arg1, arg2);
}

export function GetProgress() {
  return window['go']['main']['App']['GetProgress']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function StopBruteForce() {
  return window['go']['main']['App']['StopBruteForce']();
}
